from pathlib import Path


BASE_DIR = Path(__file__).resolve().parents[1]
UI_DIR = BASE_DIR / "ui"
ICON_DIR = BASE_DIR / "icon"
LOG_DIR = BASE_DIR / "Data"

POLL_INTERVAL_MS = 500
LOG_INTERVAL_MS = 300_000
SETPOINT_POLL_INTERVAL_MS = 1000
MEASURE_PERCENT_POLL_INTERVAL_MS = 750
INTERACTION_POLL_SUSPEND_MS = 150
MEASURE_PERCENT_UI_EPSILON = 0.2
MEASURE_FLOW_UI_EPSILON = 1e-3

SECONDS_PER_MINUTE = 60
TELEMETRY_QUEUE_TICK_MS = 200
STATUS_MESSAGE_TIMEOUT_MS = 3000
PORT_ERROR_STATUS_TIMEOUT_MS = 10000
DEFAULT_LOG_INTERVAL_MIN = LOG_INTERVAL_MS // (SECONDS_PER_MINUTE * 1000)
GAS_FACTORS_FILE = "gas_factors.json"